[package]
name = "syn-flood-port-scanning"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
socket2 = {version = "0.5.5", features = ["all"]}
